language: java
dist: xenial
sudo: false

jdk:
  - openjdk8

# TravisCI build is running only for coveralls.io/Coverage
# Test verification pipeline is on ci.jenkins.io

install: skip       # skip install phase as no deps are required

script:
  - mvn -DskipTests -Dmaven.javadoc.skip=true clean package

after_success:
  - mvn -P quality clean test jacoco:report coveralls:report

before_cache:
  - rm -fr $HOME/.m2/repository/org/jenkins-ci/plugins/jira

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
